"""empty message

Revision ID: 180099aadf11
Revises: 
Create Date: 2022-12-13 22:50:16.686201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180099aadf11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('consultstate', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('failed_access', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'failed_access')
    op.drop_column('user', 'consultstate')
    # ### end Alembic commands ###
