"""empty message

Revision ID: 1d8f2f6cdb99
Revises: 
Create Date: 2022-12-06 21:54:34.730030

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8f2f6cdb99'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    op.drop_table('feedback')
    op.drop_table('graph')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('graph',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('gra', sa.BOOLEAN(), nullable=True),
    sa.Column('DATE1', sa.VARCHAR(length=30), nullable=True),
    sa.Column('DATE2', sa.VARCHAR(length=30), nullable=True),
    sa.Column('DATE3', sa.VARCHAR(length=30), nullable=True),
    sa.Column('DATE4', sa.VARCHAR(length=30), nullable=True),
    sa.Column('DATE5', sa.VARCHAR(length=30), nullable=True),
    sa.Column('COVID1', sa.INTEGER(), nullable=True),
    sa.Column('COVID2', sa.INTEGER(), nullable=True),
    sa.Column('COVID3', sa.INTEGER(), nullable=True),
    sa.Column('COVID4', sa.INTEGER(), nullable=True),
    sa.Column('COVID5', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=40), nullable=True),
    sa.Column('date', sa.VARCHAR(length=50), nullable=True),
    sa.Column('email', sa.VARCHAR(length=50), nullable=True),
    sa.Column('subject', sa.VARCHAR(length=50), nullable=True),
    sa.Column('description', sa.VARCHAR(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('img_file_name', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('price', sa.FLOAT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=True),
    sa.Column('short_description', sa.VARCHAR(length=100), nullable=True),
    sa.Column('long_description', sa.VARCHAR(), nullable=True),
    sa.Column('stock', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
